#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Don't know how to check that this is running only on staged files. Something that might be usefull:
# lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents

yarn lint-staged